version: '3'
services:
  api:
    image: 127.0.0.1:5000/buutti-api
    networks:
      - frontend
      - backend
    volumes:
      - ${BUUTTI:-..}/:/home/node/app/
    #      - /home/node/app/node_modules/
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run dev

  redis:
    image: redis:5-alpine
    networks:
      - backend
    volumes:
      - redis-data:/data
    command: redis-server

volumes:
  redis-data:

networks:
  frontend:
  backend:
    internal: true
